### ISSUE TITLE
Syrinx Overview of Services for Home Page & Services Page - Attachment Enclosed

### ISSUE THREAD

**Issue by SyrinxCC** [Syrinx/Syrinx.github.io#12]
Upload this image to Home Page and Services Page.

We don't love the arrow but it's all we have for now - it's meant to be a visual overview of our overall services and specialty areas.

Insert image on home page under main header image. Image Title (header above image) 'Syrinx Consulting --> Software Strategy, Design, Development & Delivery'

Insert image on services page under main header image. Image Title (header above image) 'Syrinx Consulting --> Software Strategy, Design, Development & Delivery'

[Overview.pptx](https://github.com/Syrinx/Syrinx.github.io/files/326416/Overview.pptx)

**Comment by richardrissanen** [comment]
I do not see an arrow. Could this image please be provided in a png or at least a jpg.

This is what I see opening that file:

<img width="1165" alt="overview" src="https://cloud.githubusercontent.com/assets/501822/16315215/49d2c260-394f-11e6-909a-139dad4e2870.png">

**Comment by richardrissanen** [comment]
Blocked until appropriate format with entire image is made available.

**Comment by TonyMastroianni** [comment]
Recommend we break down this slide into responsive HTML for mobile-friendly viewing, and re-scope the effort.

**Comment by richardrissanen** [comment]
@TonyMastroianni Mostly done but still need a file that shows all of the elements: [https://github.com/Syrinx/Syrinx.github.io/commit/b63a79aa66a71d708bc72782431b0cea8a75299d](https://github.com/Syrinx/Syrinx.github.io/commit/b63a79aa66a71d708bc72782431b0cea8a75299d)
