### ISSUE TITLE
AWS version of Xamarin page should redirect to /xamarin on the main site.

### ISSUE THREAD

**Issue by jarrodtaylor** [Syrinx/Syrinx.github.io#15]

**Comment by jarrodtaylor** [comment]
http://syrinx.com.s3.amazonaws.com/BuildAmazingMobileApps/index.html

**Comment by richardrissanen** [comment]
Need creds in order to start this task.

**Comment by SyrinxCC** [comment]
Just emailed you...

**Comment by richardrissanen** [comment]
Have creds and will make this change post xamarin branch launching. Unless otherwise told.
