### ISSUE TITLE
Update job listings to pull from Dice

### ISSUE THREAD

**Issue by jarrodtaylor** [Syrinx/Syrinx.github.io#2]

**Comment by richardrissanen** [comment]
Blocked currently until someone can get us developer credentials for the private dice API.

**Comment by richardrissanen** [comment]
After not finding anything on the site I called support and was referred to a rep who is not in office. I sent an email and will be following up with a call to his direct line tomorrow when he has returned.

**Comment by richardrissanen** [comment]
Closed due to not being able to do from dice api
