### ISSUE TITLE
Blog from the wiki?

### ISSUE THREAD

**Issue by jarrodtaylor** [Syrinx/Syrinx.github.io#4]
It may be possible to pull blog posts from the Github wiki (the EmberJS site does this). This might be a better option than storing local Markdown files. It would allow anyone on the collaborators list to work on the blog, not just developers.

**Comment by SyrinxCC** [comment]
Jarrod - can you let us know who can make the final decision here and what are the next steps?

**Comment by richardrissanen** [comment]
I am concerned that this could lead to developers posting things in the wiki that end up public because the wiki is no longer private.

**Comment by jarrodtaylor** [comment]
Is it private now? Either way, this seems like too roundabout of an idea. It adds another external requirement to the build process.
