### ISSUE TITLE
Xamarin Premier Consulting Partner

### ISSUE THREAD

**Issue by jarrodtaylor** [Syrinx/Syrinx.github.io#5]
Add under mobile on services

**Comment by richardrissanen** [comment]
Context?

**Comment by jarrodtaylor** [comment]
When we mention being a partner with Xamarin, the term is "Xamarin Premier Consulting Partner". That should be mentioned on the services page under mobile. Possibly with other copy listed in another issue.

**Comment by SyrinxCC** [comment]
Yes thanks and we can use that logo as a clickable link to the Xamarin landing page.

**Comment by richardrissanen** [comment]
Added the text in the header for the section for the services page. Added a link but did not use the the logo as it does NOT look clickable and would be skipped over. The logo also breaks all link conventions set forth across the site, another reason a user would not click on it. 

[Example of the logo on xamarin page](https://github.com/Syrinx/Syrinx.github.io/pull/17#issuecomment-228117092)

[Example of the link on services looking clickable](https://github.com/Syrinx/Syrinx.github.io/pull/17#issuecomment-228118580)
